scoring:
  renko_weight: 2.0
  fib_weight: 1.5
  rsi_weight: 1.0
  sr_weight: 1.5
  macd_weight: 1.0
  threshold: 4.0

position_manager:
  take_profit: 0.005
  stop_loss: 0.003
  hold_candles: 2

safety_filter:
  max_rsi: 75
  min_rsi: 20
  max_atr: 1000
  macd_min: -100

circuit_breaker:
  max_daily_loss: 100
  max_consecutive_losses: 3
