profiles:
  scalping:
    symbol: "SUIUSDT"
    timeframe: "5m"
    indicators:
      rsi_period: 14
      ema_fast: 9
      ema_slow: 21
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
    scoring_weights:
      renko_weight: 0.1
      fib_weight: 0.1
      rsi_weight: 0.3
      sr_weight: 0.1
      macd_weight: 0.2
      ema_weight: 0.1
      volume_weight: 0.1
      threshold: 3
    risk:
      position_size: 0.05
      stop_loss: 1.5
      take_profit: 3

  swing:
    symbol: "SUIUSDT"
    timeframe: "1h"
    indicators:
      rsi_period: 14
      ema_fast: 20
      ema_slow: 50
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
    scoring_weights:
      renko_weight: 0.1
      fib_weight: 0.1
      rsi_weight: 0.25
      sr_weight: 0.1
      macd_weight: 0.25
      ema_weight: 0.1
      volume_weight: 0.1
      threshold: 3
    risk:
      position_size: 0.1
      stop_loss: 3
      take_profit: 6

  momentum:
    symbol: "SUIUSDT"
    timeframe: "15m"
    indicators:
      rsi_period: 10
      ema_fast: 5
      ema_slow: 15
      macd_fast: 8
      macd_slow: 18
      macd_signal: 5
    scoring_weights:
      renko_weight: 0.1
      fib_weight: 0.1
      rsi_weight: 0.4
      sr_weight: 0.1
      macd_weight: 0.2
      ema_weight: 0.05
      volume_weight: 0.05
      threshold: 3
    risk:
      position_size: 0.08
      stop_loss: 2
      take_profit: 4
